image: docker

services:
 - docker:dind

before_script:
 - export
 - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  script:
    - docker pull $CI_REGISTRY/nympok/skillbox
    - docker build --tag $CI_REGISTRY/nympok/skillbox:$CI_BUILD_REF --tag $CI_REGISTRY/nympok/skillbox:latest .
    - docker push $CI_REGISTRY/nympok/skillbox:$CI_BUILD_REF
    - docker push $CI_REGISTRY/nympok/skillbox:latest
