image: docker

services:
 - docker:dind

before_script:
 - export
 - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

buid:
  script:
    - docker build -t registry.gitlab.com/nympok/skillbox .
    - docker push registry.gitlab.com/nympok/skillbox
